theme:
  name: mkdocs
  local: en
  color_mode: auto
  nav_style: primary
  highlightjs: True
  hljs_style: github
  hljs_style_dark: github_dark

site_name: Documentation Pipeline BILL
repo_url: https://github.com/souliera/test-doc
repo_name: test-doc
site_desciption: Documentation of BILL's Pipeline
site_author: Catherine Breton, Arnaud Soulier

nav:
  - Home: index.md
  - About: about.md
